{
 "title": "System",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "存储",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SDCardOccupancyRate AS \"内存卡\",\n  HDDOccupancyRate AS \"硬盘\"\nFROM DeviceStatus\nORDER BY RecordTime desc\nlimit 1"
    }
   ]
  },
  {
   "title": "系统",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CPUOccupancyRate AS \"CPU占用率\",\n  CPUTemperature AS \"CPU温度\",\n  RAMOccupancyRate AS \"内存占用率\"\nFROM DeviceStatus\nORDER BY RecordTime desc\nlimit 1"
    }
   ]
  },
  {
   "title": "网络",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KB/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(RecordTime) AS \"time\",\n  Upload AS \"上传\",\n  Download AS \"下载\"\nFROM DeviceStatus\nWHERE\n  $__timeFilter(RecordTime)\nORDER BY RecordTime"
    }
   ]
  },
  {
   "title": "系统监控",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(RecordTime) AS \"time\",\n  CPUOccupancyRate AS \"CPU占用率\",\n  RAMOccupancyRate AS \"内存占用率\"\nFROM DeviceStatus\nWHERE\n  $__timeFilter(RecordTime)\nORDER BY RecordTime"
    }
   ]
  },
  {
   "title": "网络监控",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(RecordTime) AS \"time\",\n  Upload AS \"上传\",\n  Download AS \"下载\"\nFROM DeviceStatus\nWHERE\n  $__timeFilter(RecordTime)\nORDER BY RecordTime"
    }
   ]
  }
 ]
}